name: Build static GTFS

on:
  schedule:
    - cron: "10 18 * * *"   # UTC (JST 03:10)
  workflow_dispatch: {}

concurrency:
  group: static-gtfs
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GTFS_STATIC_ZIP_URL: ${{ secrets.GTFS_STATIC_ZIP_URL }}
      ROUTE_ID_FILTER: ""   # 例: "41102,41103" で特定路線だけ
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # 任意：unzipが無い環境への保険
      - name: Ensure unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Compose URL
        shell: bash
        run: |
          set -euo pipefail
          if [[ -n "${ODPT_KEY:-}" ]]; then
            BASE_URL="https://api.odpt.org/api/v4/files/odpt/TransportationBureau_CityOfKawasaki/AllLines.zip"
            if [[ -n "${DATE:-}" ]]; then
              URL="${BASE_URL}?date=${DATE}&acl:consumerKey=${ODPT_KEY}"
            else
              URL="${BASE_URL}?acl:consumerKey=${ODPT_KEY}"
            fi
          elif [[ -n "${GTFS_STATIC_ZIP_URL:-}" ]]; then
            URL="${GTFS_STATIC_ZIP_URL}"
          else
            echo "No URL/KEY provided." >&2; exit 1
          fi
          echo "$URL" > url.txt
          echo "Using URL (masked):"
          sed -E 's/(acl:consumerKey=)[^& ]+/\1***MASKED***/' url.txt

      - name: Download ZIP (follow redirects) & verify
        shell: bash
        run: |
          set -euo pipefail
          URL=$(cat url.txt)
          curl -fSL --retry 3 --retry-all-errors "$URL" -o gtfs.zip
          unzip -t gtfs.zip
          rm -rf gtfs_static
          mkdir -p gtfs_static
          unzip -jo gtfs.zip -d gtfs_static
          echo "Extracted files:"
          ls -l gtfs_static
          for f in stops.txt routes.txt trips.txt stop_times.txt; do
            [[ -s "gtfs_static/$f" ]] || { echo "Missing $f"; exit 1; }
          done

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build static JSON (core tables + split stop_times)
        run: |
          node scripts/make-static-json.mjs --zip gtfs.zip
        
      - name: Build calendar JSON
        run: |
          node scripts/make-calendars.mjs --zip gtfs.zip

      - name: Commit docs/*
        shell: bash
        run: |
          set -e
      
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
          # 変更がなければ終了
          git add -A docs || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
      
          git commit -m "chore: update static GTFS JSON"
      
          # 競合回避：最新mainへrebaseしてからpush（最大3回リトライ）
          for i in 1 2 3; do
            echo "Attempt $i: rebase & push"
            git fetch origin main
            # rebase失敗時はabortしてリトライ
            if git rebase origin/main; then
              if git push origin HEAD:main; then
                echo "Pushed successfully."
                exit 0
              fi
            else
              git rebase --abort || true
            fi
            echo "Retrying..."
            sleep 2
          done
      
          echo "Failed to push after retries."
          exit 1
      
      - name: Upload build artifacts (manifest)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: static-gtfs-build
          path: |
            gtfs.zip
            gtfs_static/stops.txt
            gtfs_static/routes.txt
            gtfs_static/trips.txt
            gtfs_static/stop_times.txt
            # ▼ 再帰指定でJSON全部
            docs/**/*.json
