name: Build slim static GTFS (route-filtered)

on:
  workflow_dispatch:
    inputs:
      route_ids:
        description: "route_idをカンマ区切りで（例: 1001,1002）"
        required: false
      route_short_regex:
        description: "route_short_nameの正規表現（例: ^(溝口|たいら)$）"
        required: false
  schedule:
    - cron: "0 18 * * *"  # 毎日(UTC18:00)。必要に応じて変更

permissions:
  contents: write

jobs:
  build-slim-gtfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm i csv-parse@^5

      - name: Download GTFS static zip
        run: |
          curl -L "$GTFS_STATIC_ZIP_URL" -o gtfs.zip
          rm -rf gtfs_static && mkdir gtfs_static
          unzip -o gtfs.zip -d gtfs_static
        env:
          GTFS_STATIC_ZIP_URL: ${{ secrets.GTFS_STATIC_ZIP_URL }}

      - name: Build slim JSONs
        run: |
          node scripts/build-static-gtfs.mjs
        env:
          # フィルタ条件（どちらか/両方使えます）
          ROUTE_ID_LIST: ${{ github.event.inputs.route_ids }}
          ROUTE_SHORT_NAME_REGEX: ${{ github.event.inputs.route_short_regex }}

          # 起点・終点（必要なければ空のままでもOK）
          ORIGIN_STOP_ID: "260_1"
          DEST_STOP_ID: "434_5"

      - name: Commit slim JSONs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: slim static GTFS (route filtered)"
          file_pattern: docs/stops.json docs/trips.json docs/stop_times.json docs/routes.json
