# .github/workflows/static-gtfs.yml
name: Build static GTFS

on:
  schedule:
    - cron: "10 18 * * *"   # UTC。JST 03:10 相当
  workflow_dispatch: {}

concurrency:
  group: static-gtfs
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      # ① 丸ごとURLをSecretに入れている場合（推奨その1）
      GTFS_STATIC_ZIP_URL: ${{ secrets.GTFS_STATIC_ZIP_URL }}
      # 必要路線だけに絞るならカンマ区切りで（例: "41102,41103"）
      ROUTE_ID_FILTER: ""
    steps:
      - uses: actions/checkout@v4

      - name: Compose URL
        shell: bash
        run: |
          set -euo pipefail
          if [[ -n "${ODPT_KEY:-}" ]]; then
            if [[ -n "${DATE:-}" ]]; then
              URL="${BASE_URL}?date=${DATE}&acl:consumerKey=${ODPT_KEY}"
            else
              URL="${BASE_URL}?acl:consumerKey=${ODPT_KEY}"
            fi
            echo "$URL" > url.txt
            echo "Use: BASE_URL + ODPT_KEY (masked)"
          elif [[ -n "${GTFS_STATIC_ZIP_URL:-}" ]]; then
            echo "$GTFS_STATIC_ZIP_URL" > url.txt
            echo "Use: GTFS_STATIC_ZIP_URL secret"
          else
            echo "No URL/KEY provided. Set either GTFS_STATIC_ZIP_URL or ODPT_KEY." >&2
            exit 1
          fi
          sed -E 's/(acl:consumerKey=)[^& ]+/\1***MASKED***/' url.txt

      - name: Download ZIP (follow redirects) & verify
        shell: bash
        run: |
          set -euo pipefail
          URL=$(cat url.txt)
          curl -fSL --retry 3 --retry-all-errors "$URL" -o gtfs.zip
      
          # ZIP破損チェック
          unzip -t gtfs.zip
      
          # フラットに展開（サブフォルダを無視して直下に並べる）
          rm -rf gtfs_static
          mkdir -p gtfs_static
          unzip -jo gtfs.zip -d gtfs_static
      
          echo "Extracted files:"
          ls -l gtfs_static
      
          # 必須4種の存在チェック
          for f in stops.txt routes.txt trips.txt stop_times.txt; do
            if [[ ! -s "gtfs_static/$f" ]]; then
              echo "Missing required file: gtfs_static/$f" >&2
              exit 1
            fi
          done
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps for converter
        run: npm i csv-parse@5.x

      - name: Convert TXT -> JSON (slim build)
        env:
          ROUTE_ID_FILTER: ${{ env.ROUTE_ID_FILTER }}
        run: |
          node scripts/build-static-gtfs.mjs

      - name: Commit docs/*
        shell: bash
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/*.json || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update static GTFS JSON"
            git push
          fi

      - name: Upload build artifacts (manifest)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: static-gtfs-build
          path: |
            gtfs.zip
            gtfs_txt/stops.txt
            gtfs_txt/routes.txt
            gtfs_txt/trips.txt
            gtfs_txt/stop_times.txt
            docs/*.json
